[package]
name = "ultim_admin"
version = "0.1.0"
edition = "2021"

[dependencies]
ultim = { path = "../../ultim" }
log = "0.4.20"
serde_json = "1.0.108"
actix-web = "4.4.0"
diesel = "2.1.4"

[lib]
crate-type = ["dylib"]
